FROM oven/bun:1

WORKDIR /usr/src/app 

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./apps/backend ./apps/backend
COPY ./turbo.json ./turbo.json
RUN bun install 




RUN bun run generate:db


EXPOSE 8080
CMD [ "bun","run","start:backend" ]