FROM oven/bun:1


ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

WORKDIR /usr/src/app 

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./apps/web ./apps/web
COPY ./turbo.json ./turbo.json
RUN bun install 

RUN apt-get update && apt-get install -y openssl
RUN apt-get update && apt-get install -y npm




RUN echo "Database URL is: $DATABASE_URL"


RUN bun run generate:db
RUN bun run build:frontend


EXPOSE 3000
CMD [ "bun","run","start:frontend" ]  